Repository FRONTENDSCHOOL8/popcorn-euid, pull requests merged in 2024-01, with the labels that each got.

#18 login 환경 설정 완료
  src/pages/login/index.html
  src/pages/login/login.js
Labels: feature

#43 Feature/profile
  index.html
  public/images/Q&A.svg
  public/images/alramBell.svg
  public/images/board-hamburger.svg
  public/images/calender.svg
  public/images/checkBox.svg
  public/images/checkBox_uncheck.svg
  public/images/close.svg
  public/images/direction.svg
  public/images/fullpeople.svg
  public/images/heart.svg
  public/images/information.svg
  public/images/more.svg
  public/images/pencil.svg
  public/images/people.svg
  public/images/profile.svg
  public/images/right.svg
  public/images/search.svg
  public/images/speech.svg
  public/images/temperatureAngle.svg
  src/assets/enroll.jpg
  src/assets/profileTest.jpg
  src/pages/exchange/index.html
  src/pages/profile/index.html
  src/styles/tailwind.css
  tailwind.config.js
Labels: feature

#42 feat : start 페이지 구현
  public/images/logo.svg
  src/pages/start/index.html
  src/pages/start/start.js
  src/pages/template/index.html
  vite.config.js
Labels: feature

#45 feat : category 페이지 구현 - iamjinpark
  public/images/check.svg
  public/images/directionL.svg
  public/images/plus.svg
  src/pages/category/category.js
  src/pages/category/index.html
  src/styles/tailwind.css
Labels: feature

#44 feat : board페이지 + togetherBoard 페이지 - taewook
  docs/assets/board-contest-f0gTIC6v.svg
  docs/assets/board-emogi-bkPhdjpb.svg
  docs/assets/board-offline-MhpHYWL9.svg
  docs/assets/board-project-eJDVNsOF.svg
  docs/assets/board-study-a93vG-NK.svg
  docs/assets/hooray-YbVsADzr.png
  docs/assets/tailwind-IQ-Xsqy0.css
  docs/assets/tailwind-_qHBtFOa.js
  docs/assets/tailwind-b7llmXQZ.css
  docs/assets/tailwind-po9p4yZ2.js
  docs/images/alramBell.png
  docs/images/alramBell.svg
  docs/images/board-contest.svg
  docs/images/board-emogi.svg
  docs/images/board-hamburger.svg
  docs/images/board-offline.svg
  docs/images/board-project.svg
  docs/images/board-study.svg
  docs/images/calender.svg
  docs/images/chat.svg
  docs/images/close.svg
  docs/images/direction.png
  docs/images/direction.svg
  docs/images/directionL.svg
  docs/images/fullHome.svg
  docs/images/fullpeople.svg
  docs/images/hamburger.png
  docs/images/hamburger.svg
  docs/images/hooray.png
  docs/images/life.svg
  docs/images/map.svg
  docs/images/my.svg
  docs/images/people.svg
  docs/images/search.png
  docs/images/search.svg
  docs/index.html
  docs/src/pages/board/index.html
  docs/src/pages/story/index.html
  docs/src/pages/togetherBoard/index.html
  public/images/board-contest.svg
  public/images/board-emogi.svg
  public/images/board-offline.svg
  public/images/board-project.svg
  public/images/board-study.svg
  src/pages/board/board.js
  src/pages/board/index.html
  src/pages/togetherBoard/index.html
  src/pages/togetherBoard/togetherBoard.js
  src/styles/tailwind.css
  vite.config.js
Labels: feature

#46 modify : start css 코드 수정 - iamjinpark
  src/pages/start/index.html
Labels: feature

#57 feat: profile 페이지 문법 오류 수정 및 vite.config 경로추가-vhwav
  src/pages/profile/index.html
  vite.config.js
Labels: feature

#58 Feature/story
  src/pages/story/index.html
  tailwind.config.js
Labels: documentation

#61 feat : togetherBoard에 plusTap 버튼 추가 - taewook
  public/images/plusTap.svg
  public/images/plusTapActive.svg
  src/pages/togetherBoard/index.html
Labels: feature

#64 feat: writeBoard2 마크업 - taewook
  public/images/calenderBlack.svg
  public/images/directionDown.svg
  public/images/minus-board-people.svg
  public/images/plus-board-people.svg
  public/images/time.svg
  src/pages/writeBoardSecond/index.html
  src/pages/writeBoardSecond/writeBoardSecond.js
  vite.config.js
Labels: feature

#65 Feature/exchange
  public/images/heart.svg
  public/images/hello.png
  public/images/home.svg
  public/images/more.svg
  public/images/share.svg
  src/pages/exchange/exchange.js
  src/pages/exchange/index.html
  src/pages/exchangeBoard/exchangeBoard.js
  src/pages/exchangeBoard/index.html
  src/styles/tailwind.css
  vite.config.js
Labels: modify

#66 modify: board 페이지 마크업 수정,선택자 생성 - taewook
  src/pages/board/index.html
Labels: modify

#68 modifiy: togetherBoard 마크업 수정, figure를 button으로 변경 - taewook
  src/pages/togetherBoard/index.html
Labels: modify

#67 Feature/exchange board
  public/images/directionL.svg
  public/images/heart.svg
  public/images/macbook20.png
  public/images/more.svg
  src/pages/exchangeBoard/index.html
  vite.config.js
Labels: modify

#71 feat: writeBoardThird 페이지 마크업 - taewook
  public/images/password.svg
  public/images/sex.svg
  public/images/toggle.svg
  public/images/toggleFocus.svg
  src/pages/writeBoardThird/index.html
  src/pages/writeBoardThird/writeBoardThird.js
  vite.config.js
Labels: feature

#72 modify: writeBoardSecond vite.config.js 페이지 경로 수정 -taewook
  src/pages/writeBoardSecond/index.html
  vite.config.js
Labels: modify

#73 feat: chat screen 페이지 마크업 - taewook
  public/images/plusChatScreen.svg
  public/images/send.svg
  public/images/smile.svg
  src/pages/chatScreen/chatScreen.js
  src/pages/chatScreen/index.html
  vite.config.js
Labels: feature

#77 fixs : vite.config 내용 수정
  vite.config.js
Labels: bug

#78 Feature/signup
  src/pages/category/index.html
  src/pages/signUp/index.html
  src/pages/signUp/signUp.js
  src/pages/start/index.html
  src/styles/tailwind.css
  vite.config.js
Labels: feature

#79 Modify : 뒤로가기 버튼 태그로 수정 - iamjinpark
  src/pages/signUp/index.html
Labels: feature

#80 page-writeBoard 마크업 - taewook
  src/pages/writeBoard/index.html
  src/pages/writeBoard/writeBoard.js
  vite.config.js
Labels: feature

#83 Feature/profile details 페이지 구현 및 충돌 해결
  public/images/passwordDetails.svg
  public/images/peoplePublic.svg
  public/images/plusProfile.svg
  src/pages/profileDetails/index.html
  src/pages/profileDetails/profileDetails.js
  src/styles/tailwind.css
  tailwind.config.js
  vite.config.js
Labels: feature

#84 modify:writeBoard 페이지의 h1 sr-only 수정-taewook
  src/pages/writeBoard/index.html
Labels: modify

#85 Feature/profile card 페이지 구현
  .prettierrc.cjs
  src/pages/profile/index.html
  src/pages/profileCard/index.html
  src/pages/profileCard/profileCard.js
  src/styles/tailwind.css
Labels: feature

#87 modify:(writeBoard 뒤로가기버튼으로변경)(writeBoardSecond 뒤로가기버튼으로 변경) (writeBo…
  src/pages/writeBoard/index.html
  src/pages/writeBoardSecond/index.html
  src/pages/writeBoardThird/index.html
  src/styles/tailwind.css
  vite.config.js
Labels: modify

#86 Modify : 뒤로가기 태그 및 className 수정 - iamjinpark
  src/pages/category/index.html
  src/styles/tailwind.css
  vite.config.js
Labels: feature

#91 feat : login 페이지 구현 - iamjinpark
  src/pages/login/index.html
Labels: feature

#92 docs : vite.config에 login 페이지 추가 - iamjinpark
  vite.config.js
Labels: feature

#90 Feature/search
  public/images/directionL.svg
  src/pages/search/index.html
  src/pages/search/search.js
  src/styles/tailwind.css
  vite.config.js
Labels: feature

#94 feat: writeboard container 통합 작업
  src/pages/writeBoard/index.html
Labels: feature

#96 Feature/chat
  public/images/Group.svg
  public/images/call.svg
  public/images/more.svg
  public/images/plus.svg
  public/images/won.svg
  src/pages/chat/chat.js
  src/pages/chat/index.html
  src/styles/tailwind.css
Labels: feature

#99 feat : component 수정
  public/images/fullheart.svg
  src/pages/chat/index.html
  src/pages/components/boardNav/index.html
  src/pages/components/boardNav/template.js
  src/pages/components/headNav/index.html
  src/pages/components/homeNav/index.html
  src/pages/exchange/index.html
  src/pages/exchangeBoard/index.html
  src/pages/story/index.html
  src/styles/tailwind.css
Labels: feature

#100 modify : plus 아이콘 img -> button으로 수정 -iamjinpark
  public/images/checked.svg
  src/pages/category/category.js
  src/pages/category/index.html
  src/styles/tailwind.css
Labels: feature

#104 modify : input 태그로 변경 - iamjinpark
  src/pages/category/category.js
  src/pages/category/index.html
  src/styles/tailwind.css
Labels: feature

#106 modify: +버튼에 bg-background 추가 - taewook
  src/pages/chatScreen/index.html
  src/pages/togetherBoard/index.html
Labels: modify

#110 feat : page 연결 및 간단한 버튼 기능 구현
  public/images/fullMap.svg
  src/pages/chat/chat.js
  src/pages/chat/index.html
  src/pages/components/boardNav/index.html
  src/pages/components/homeNav/index.html
  src/pages/exchange/exchange.js
  src/pages/exchange/index.html
  src/pages/exchangeBoard/exchangeBoard.js
  src/pages/exchangeBoard/index.html
  src/pages/search/index.html
  src/pages/search/search.js
  src/pages/story/index.html
  src/styles/tailwind.css
  tailwind.config.js
Labels: feature

#112 modify : w-screen 추가 및 js로 페이지 이동 구현 - iamjinpark
  src/pages/signUp/index.html
  src/pages/signUp/signUp.js
Labels: feature

#113 modify : 뒤로가기 버튼 a -> button 으로 수정 - iamjinpark
  src/pages/signUp/index.html
  src/pages/signUp/signUp.js
Labels: feature

#114 feat: page 연결 및 profile 의 figure>div로 변경 - vHwav
  src/pages/profile/index.html
  src/pages/profileCard/index.html
  src/pages/profileDetails/index.html
Labels: feature

#115 feat: board <-> chatScreen 화면 연결 + swipe,gsap npm 설치 - taewook
  package-lock.json
  package.json
  public/images/fullFile.svg
  src/pages/board/board.js
  src/pages/board/index.html
  src/pages/components/homeNav/homeNav.js
  src/pages/components/homeNav/index.html
  src/pages/togetherBoard/index.html
  src/pages/togetherBoard/togetherBoard.js
  src/pages/writeBoard/index.html
  src/pages/writeBoard/writeBoard.js
Labels: feature

#117 feat : 버튼 기능 추가
  src/pages/exchange/exchange.js
  src/pages/exchange/index.html
  src/pages/exchangeBoard/exchangeBoard.js
  src/pages/exchangeBoard/index.html
  src/styles/tailwind.css
Labels: feature

#118 modify: board 페이지 마크업 수정 - taewook
  src/pages/board/index.html
Labels: feature

#123 modify : 중간점검 전 수정
  src/pages/components/headNav/index.html
  src/pages/components/homeNav/index.html
  src/pages/exchange/exchange.js
  src/pages/exchange/index.html
  src/pages/exchangeBoard/index.html
  src/pages/search/index.html
  src/pages/story/index.html
  vite.config.js
Labels: modify

#124 build: 경로 및 homeNav 추가 - vHawv
  public/images/fullMy.svg
  src/pages/components/homeNav/index.html
  src/pages/profile/index.html
  src/pages/profile/profile.js
  src/pages/profileCard/index.html
  src/pages/profileCard/profileCard.js
  src/pages/profileDetails/index.html
  src/pages/profileDetails/profileDetails.js
  src/styles/tailwind.css
Labels: modify

#130 Modify/mid
  package-lock.json
  package.json
  src/pages/exchange/exchange.js
  src/pages/exchangeBoard/exchangeBoard.js
  vite.config.js
Labels: feature

#133 featrue: togertherBoard 클릭 이벤트, writeBoard 수정 2024-01-09 -taewook
  src/pages/togetherBoard/index.html
  src/pages/togetherBoard/togetherBoard.js
  src/pages/writeBoard/writeBoard.js
Labels: bug, feature

#136 reset: confick 리셋하고 푸시 - taewook 01-09 오후 4:38
  src/pages/board/board.js
  src/pages/board/index.html
  src/pages/togetherBoard/index.html
  src/pages/togetherBoard/togetherBoard.js
  src/pages/writeBoard/index.html
  src/pages/writeBoard/writeBoard.js
  src/pages/writeBoardSecond/index.html
  src/pages/writeBoardSecond/writeBoardSecond.js
  vite.config.js
Labels: bug, modify

#137 feat : setting 초기화 01.09 16:56
  package-lock.json
  package.json
  vite.config.js
Labels: feature

#140 docs : 문서 복원 01-09 21:14
  src/pages/components/headNav/index.html
  src/pages/exchange/exchange.js
  src/pages/exchange/index.html
  src/pages/exchangeBoard/exchangeBoard.js
  src/pages/exchangeBoard/index.html
  src/pages/search/index.html
  src/pages/story/index.html
Labels: modify

#141 modify : 마크업 수정 및 hover 이벤트 추가 - iamjinpark
  src/pages/category/category.js
  src/pages/category/index.html
  src/styles/tailwind.css
  tailwind.config.js
Labels: feature

#145 exchange 기능 추가 01-10 09:54
  package.json
  src/lib/utils/getPbImageURL.js
  src/lib/utils/index.js
  src/lib/utils/timeAgo.js
  src/pages/exchange/exchange.js
  src/pages/exchange/index.html
  src/styles/tailwind.css
Labels: feature

#146 feat:profileDetails JS부분 active, toggle, agree 부분 구현 완료. 01-01-14:05 …
  public/images/passwordDetails.svg
  src/pages/category/index.html
  src/pages/profileDetails/index.html
  src/pages/profileDetails/profileDetails.js
  src/styles/tailwind.css
Labels: feature

#149 feature: 게시판 LIST 데이터 갖고오기, relation연결 - taewook 01-10오후3:31
  src/pages/board/board.js
  src/pages/board/index.html
  src/pages/togetherBoard/index.html
  src/pages/togetherBoard/togetherBoard.js
  src/pages/writeBoard/writeBoard.js
Labels: feature, modify

#150 feat : exchangeBoard 기능 추가 01-10 15:57
  src/pages/exchange/exchange.js
  src/pages/exchangeBoard/exchangeBoard.js
  src/pages/exchangeBoard/index.html
Labels: feature

#152 profile list 구현 및, 전체 homeNav 위치 수정 18:06 -vHwav-
  src/pages/profile/index.html
  src/pages/profile/profile.js
  src/pages/profileCard/index.html
  src/pages/profileCard/profileCard.js
  src/pages/profileDetails/index.html
  src/pages/profileDetails/profileDetails.js
  src/styles/tailwind.css
Labels: feature

#154 modify : 링크 연결 수정 01-11 09:05
  src/lib/utils/index.js
  src/lib/utils/removeChild.js
  src/pages/exchangeBoard/exchangeBoard.js
  src/pages/exchangeBoard/index.html
Labels: modify

#156 modify : 반복되는 함수 forEach 01-11 11:26
  src/pages/exchange/exchange.js
  src/pages/exchange/index.html
  src/pages/exchangeBoard/exchangeBoard.js
Labels: modify

#157 feat : 핸드폰 번호 valid 및 localStorage 저장 기능 구현 - iamjinpark
  src/pages/signUp/index.html
  src/pages/signUp/signUp.js
Labels: feature

#158 feat: board 주제드롭다운메뉴창 toggle 기능추가 , board 게시판 클릭시 details 화면으로 이동, w…
  public/images/passwordBoard.svg
  src/pages/board/board.js
  src/pages/board/index.html
  src/pages/boardContent/boardContent.js
  src/pages/boardContent/index.html
  src/pages/writeBoard/index.html
  src/pages/writeBoard/writeBoard.js
  src/pages/제목 없는 다이어그램.drawio
Labels: feature

#159 feature: board 쪽 페이지들 min-280px 조절, 같이해요 페이지 nav toggle 수정 및 구현 -taewook 01/11오후5:42
  src/pages/board/board.js
  src/pages/board/index.html
  src/pages/boardContent/index.html
  src/pages/chatScreen/index.html
  src/pages/togetherBoard/index.html
  src/pages/togetherBoard/togetherBoard.js
  src/pages/writeBoard/index.html
Labels: feature, modify

#160 feat : valid 체크 기능 및 로컬스토리지 저장 기능 구현 완료 - iamjinpark 01/12 3:17am
  src/pages/signUp/index.html
  src/pages/signUp/signUp.js
Labels: feature

#161 feat:profile,profileDetails데이터세팅 03:16 -vHwav
  package-lock.json
  package.json
  src/pages/profile/index.html
  src/pages/profile/profile.js
  src/pages/profileDetails/index.html
  src/pages/profileDetails/profileDetails.js
Labels: feature

#162 feat : pocketbase post 기능 구현 - iamjinpark 01/12 4:31am
  src/pages/signUp/signUp.js
Labels: feature

#163 feat : 검색 기능 구현 01-12 13:23
  public/images/1.jpg
  public/images/2.jpg
  public/images/3.jpg
  public/images/4.jpg
  src/pages/exchange/exchange.js
  src/pages/search/index.html
  src/pages/search/search.js
  src/pages/signUp/signUp.js
Labels: feature

#164 feat : 회원가입 중복 유효성 검사 구현 완료 - iamjinpark 01/12 1:47pm
  src/pages/signUp/signUp.js
Labels: feature

#166 Feature/exchange post
  public/images/camera.svg
  src/pages/exchange/exchange.js
  src/pages/exchangePost/exchangePost.js
  src/pages/exchangePost/index.html
  src/pages/signUp/signUp.js
  src/styles/tailwind.css
Labels: feature

#167 feature: 다른페이지 ui 수정, writeBoard 입력UI선택작업중 -taewook 01/12오후3:55
  src/pages/board/board.js
  src/pages/board/index.html
  src/pages/boardContent/boardContent.js
  src/pages/togetherBoard/index.html
  src/pages/togetherBoard/togetherBoard.js
  src/pages/writeBoard/index.html
  src/pages/writeBoard/writeBoard.js
Labels: feature

#168 feat : 인증번호 유효성 검사 구현 완료 - iamjinpark 01/12 4:27pm
  src/pages/signUp/index.html
  src/pages/signUp/signUp.js
Labels: feature

#170 feat : post 기능 구현 01-12 22:10
  src/pages/exchangePost/exchangePost.js
  src/pages/exchangePost/index.html
Labels: feature

#171 feature: writeboard 게시글 create 구현 나이선택제외 -taewook 01/13 오전1:24
  src/lib/utils/formattedDate.js
  src/lib/utils/formattedTime.js
  src/lib/utils/index.js
  src/pages/togetherBoard/togetherBoard.js
  src/pages/writeBoard/index.html
  src/pages/writeBoard/writeBoard.js
Labels: feature

#172 feature: togetherpage gsap적용 -taewook 01/13오전3:43
  src/lib/utils/formattedDate.js
  src/pages/board/board.js
  src/pages/togetherBoard/togetherBoard.js
Labels: feature

#173 feat : 로그인 필수 기능 구현 완료 - iamjinpark 01/13 3:44am
  src/pages/login/index.html
  src/pages/login/login.js
  src/pages/signUp/signUp.js
Labels: feature

#177 feat:profileCard 수정기능 구현 중간 저장 13:53 -vHwav-
  src/lib/utils/debounce.js
  src/lib/utils/index.js
  src/pages/profile/profile.js
  src/pages/profileCard/index.html
  src/pages/profileCard/profileCard.js
  src/styles/tailwind.css
Labels: feature

#178 feature:같이해요deatils 화면연동, delete 구현중 taewook 오후4:39
  src/pages/boardContent/boardContent.js
  src/pages/boardContent/index.html
  src/pages/chatScreen/chatScreen.js
  src/pages/chatScreen/index.html
  src/pages/togetherBoard/index.html
  src/pages/togetherBoard/togetherBoard.js
Labels: feature

#179 feat: rendering util함수 추가 및 profileCard 기능 구현 00:46 -vHwav
  src/lib/utils/index.js
  src/lib/utils/rendering.js
  src/pages/profileCard/index.html
  src/pages/profileCard/profileCard.js
  vite.config.js.timestamp-1705146579082-6193cd50cdd2d.mjs
Labels: feature

#180 feat : 좋아요 연동 구현 01-14 04:00
  src/pages/exchangeBoard/exchangeBoard.js
Labels: feature

#181 feat : 좋아요 연동 수정 01-14 07:57
  src/pages/exchangeBoard/exchangeBoard.js
  src/pages/exchangeBoard/index.html
  src/pages/exchangeEdit/exchangeEdit.js
  src/pages/exchangeEdit/index.html
Labels: feature

#184 feature: 수정메뉴바, create,delete코드 수정 taewook 01/14오후5:30
  src/pages/board/board.js
  src/pages/boardContent/boardContent.js
  src/pages/boardContent/index.html
  src/pages/togetherBoard/togetherBoard.js
  src/pages/writeBoard/writeBoard.js
Labels: bug, feature

#185 feat : 정규식 유효성 검사 수정 및 타이머 기능 추가 - iamjinpark 01/14 6:00pm
  src/pages/category/index.html
  src/pages/signUp/index.html
  src/pages/signUp/signUp.js
Labels: feature

#186 feat : 좋아요 갯수 연동 및 update페이지 구연 10-14 18:40
  src/pages/exchange/exchange.js
  src/pages/exchange/index.html
  src/pages/exchangeBoard/exchangeBoard.js
  src/pages/exchangeBoard/index.html
  src/pages/exchangeEdit/exchangeEdit.js
  src/pages/exchangeEdit/index.html
  src/styles/tailwind.css
Labels: feature

#187 feat : 타이머 기능 구현 완료 - iamjinpark 01/14 7:32pm
  src/pages/signUp/index.html
  src/pages/signUp/signUp.js
Labels: feature

#189 feat: getPbImageURL경로 수정 및 renderingPhoto 추가 19:51 -vHwav
  src/lib/utils/getPbImageURL.js
  src/lib/utils/rendering.js
  src/pages/profile/index.html
  src/pages/profile/profile.js
  src/pages/profileCard/index.html
  src/pages/profileCard/profileCard.js
  src/pages/signUp/index.html
  src/pages/signUp/signUp.js
Labels: feature

#190 feat : login 페이지 타이머 구현 완료 -iamjinpark 01/14 8:58pm
  src/pages/login/index.html
  src/pages/login/login.js
Labels: feature

#191 feat: profileCard 에러 수정 21:21 -vHwav
  src/lib/utils/rendering.js
  src/pages/profileCard/index.html
  src/pages/profileCard/profileCard.js
Labels: feature

#192 modify : getPbImageURL.js 01-14 21:42
  src/lib/utils/getPbImageURL.js
Labels: modify

#194 feat : 로컬스토리지 저장 및 포켓베이스 post 기능 구현 - iamjinpark 01/15 3:35am
  src/pages/category/category.js
  src/pages/category/index.html
Labels: feature

#193 feat: profile 배지/탈퇴 제외 마무리 01:59 -vHwav-
  src/assets/popcorn.png
  src/lib/utils/rendering.js
  src/pages/profile/index.html
  src/pages/profile/profile.js
Labels: feature

#195 feature:같이해요update구현, filter적용중 taeoowk 01/15오전6:00
  src/lib/utils/rendering.js
  src/pages/board/board.js
  src/pages/boardContent/boardContent.js
  src/pages/boardContent/index.html
  src/pages/togetherBoard/index.html
  src/pages/togetherBoard/togetherBoard.js
  src/pages/writeBoard/writeBoard.js
Labels: feature

#196 feat : chat 구현중
  src/lib/utils/rendering.js
  src/pages/chat/chat.js
  src/pages/chat/index.html
  src/pages/exchangeBoard/exchangeBoard.js
  src/pages/exchangeBoard/index.html
  src/pages/story/index.html
Labels: feature

#197 feature:같이해요페이지 filter구현 -taewook 01/15 오전9:30
  src/pages/togetherBoard/togetherBoard.js
Labels: feature

#198 feature:포커스색변환, 같이해요드롭다운메뉴 -taewook 01/15오후1:04
  src/pages/board/board.js
  src/pages/board/index.html
  src/pages/boardContent/boardContent.js
  src/pages/boardContent/index.html
  src/pages/togetherBoard/index.html
  src/pages/togetherBoard/togetherBoard.js
  src/pages/writeBoard/index.html
  src/pages/writeBoard/writeBoard.js
  tailwind.config.js
Labels: feature

#199 feat : 채팅방 구현 01-15 13:55
  src/pages/chat/chat.js
  src/pages/exchangeBoard/exchangeBoard.js
Labels: feature

#200 modify : 카테고리 및 회원가입 서버 전송코드 수정 - iamjinpark 01/15 3:35pm
  src/pages/category/category.js
  src/pages/category/index.html
  src/pages/login/login.js
  src/pages/signUp/signUp.js
  src/pages/start/index.html
Labels: feature

#201 feat : 채팅창 구현중
  src/pages/chat/chat.js
  src/pages/chat/index.html
Labels: feature

#202 modify:주석,연속수정하기 수정 tawook1212 01/15오후3:59
  src/pages/board/board.js
  src/pages/board/index.html
  src/pages/boardContent/boardContent.js
  src/pages/boardContent/index.html
  src/pages/togetherBoard/index.html
  src/pages/togetherBoard/togetherBoard.js
  src/pages/writeBoard/index.html
  src/pages/writeBoard/writeBoard.js
Labels: modify

#204 modify : index.html 파일 수정 (경로 이슈) - iamjinpark 01/15 4:13pm
  index.html
  src/pages/start/index.html
Labels: bug

#205 modify : 경로 수정 01-15 17:28
  src/pages/exchange/exchange.js
  vite.config.js
Labels: feature

#206 modify : 에러메세지 추가 및 카테고리 서치 항목 제거 - iamjinpark 01/16 12:02am
  index.html
  src/pages/category/category.js
  src/pages/category/index.html
  src/pages/login/index.html
  src/pages/login/login.js
  src/pages/signUp/index.html
  src/pages/signUp/signUp.js
  tailwind.config.js
Labels: modify

#207 feat : 채팅 내용 구현 01-16 00:18
  src/pages/chat/chat.js
Labels: feature

#208 feat: profileDetails 하는 일 미완 02:49 -vHwav
  src/pages/profileCard/index.html
  src/pages/profileCard/profileCard.js
  src/pages/profileDetails/index.html
  src/pages/profileDetails/profileDetails.js
Labels: feature

#214 Modify/story
  public/images/멋사넷.webp
  public/images/멋사둘.webp
  public/images/멋사셋.webp
  public/images/멋사하나.png
  public/images/수면좋아.png
  public/images/스크럼좋아.png
  public/images/응마박.png
  public/images/출근좋아.png
  src/pages/signUp/signUp.js
  src/pages/story/index.html
Labels: modify

#231 featuer: 검색기능 범위추가 및 board에도 연결 +commnity taewook 01/25 오전1:15
  src/pages/board/index.html
  src/pages/search/search.js
Labels: feature
